steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: pack
    args:
      - build
      - 'asia-south2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/evmglobal/evmglobal:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:google-22'
      - '--path=server'
      - '--env=GOOGLE_NODE_RUN_SCRIPTS=build'
      - '--publish'
    id: Build

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - evmglobal
      - '--platform=managed'
      - '--region=asia-south2'
      - '--image=asia-south2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/evmglobal/evmglobal:$COMMIT_SHA'
    id: Deploy

images:
  - 'asia-south2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/evmglobal/evmglobal:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
