steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/evmglobal:$COMMIT_SHA'
      - '-f'
      - 'server/Dockerfile'
      - './server'
    id: Build

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/evmglobal:$COMMIT_SHA'
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - emvglobal
      - '--platform=managed'
      - '--region=asia-south2'
      - '--image=gcr.io/$PROJECT_ID/evmglobal:$COMMIT_SHA'
    id: Deploy

images:
  - 'gcr.io/$PROJECT_ID/evmglobal:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
